spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/insurancemanagementsystem?&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: 'true'
    mode: HTML5
    prefix: 'classpath:/templates/'
    suffix: '.html'
    servlet:
      content-type: 'text/html'
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100000000